[package]
name = "polint-core"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true
readme.workspace = true
description.workspace = true

[dependencies]
anyhow.workspace = true
polint-diagnostics = { workspace = true }
rayon.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
