[package]
name = "polint-rules"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
globset.workspace = true
polint-config = { path = "../polint-config" }
polint-core = { path = "../polint-core" }
polint-diagnostics = { path = "../polint-diagnostics" }
polint-sdk = { path = "../polint-sdk" }

[dev-dependencies]
insta.workspace = true
serde_json.workspace = true
