[workspace]
include = ["payment_test.go"]
exclude = []

[profiles.fast]
rules = ["examples/go-test-suite-size", "examples/go-assertion-after-action"]

[[rules.config]]
id = "examples/go-test-suite-size"
max = 0
files = ["*_test.go"]

[[rules.config]]
id = "examples/go-assertion-after-action"
files = ["*_test.go"]
