[package]
name = "polint-config"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true
readme.workspace = true
description.workspace = true

[dependencies]
anyhow.workspace = true
globset.workspace = true
serde.workspace = true
thiserror.workspace = true
toml.workspace = true
