[package]
name = "polint-example-rules"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "polint-example-rules"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
globset.workspace = true
polint-cache = { path = "../../crates/polint-cache" }
polint-config = { path = "../../crates/polint-config" }
polint-core = { path = "../../crates/polint-core" }
polint-diagnostics = { path = "../../crates/polint-diagnostics" }
polint-fs = { path = "../../crates/polint-fs" }
polint-go = { path = "../../crates/polint-go" }
polint-sdk = { path = "../../crates/polint-sdk" }
polint-ts = { path = "../../crates/polint-ts" }
serde_json.workspace = true

[dev-dependencies]
insta.workspace = true
