[package]
name = "polint-frontend-api"
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true
description = "LanguageFrontend contracts for polint"

[dependencies]
polint-core.workspace = true
polint-analysis-api.workspace = true

[lints]
workspace = true
