[package]
name = "polint-cli"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "polint"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
polint-cache = { path = "../polint-cache" }
polint-config = { path = "../polint-config" }
polint-core = { path = "../polint-core" }
polint-diagnostics = { path = "../polint-diagnostics" }
polint-fs = { path = "../polint-fs" }
polint-go = { path = "../polint-go" }
polint-graph = { path = "../polint-graph" }
polint-plugin = { path = "../polint-plugin" }
polint-rules = { path = "../polint-rules" }
polint-ts = { path = "../polint-ts" }
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
tempfile.workspace = true
