[package]
name = "polint-plugin"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = []
wasmtime-host = ["dep:wasmtime", "dep:wit-bindgen"]

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
wasmtime = { workspace = true, optional = true }
wit-bindgen = { workspace = true, optional = true }
