[package]
name = "polint-go"
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true
description = "Go language frontend, sidecar integration, and Go syntax/semantic stores for polint"

[dependencies]
anyhow.workspace = true
polint-analysis-api.workspace = true
polint-core.workspace = true
polint-frontend-api.workspace = true
polint-ir.workspace = true
rayon.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true
toml.workspace = true
tree-sitter.workspace = true
tree-sitter-go.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
