[package]
name = "polint-go"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
polint-cache = { path = "../polint-cache" }
polint-core = { path = "../polint-core" }
polint-diagnostics = { path = "../polint-diagnostics" }
tree-sitter.workspace = true
tree-sitter-go.workspace = true

[dev-dependencies]
polint-graph = { path = "../polint-graph" }
