[package]
name = "polint-sdk"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
polint-core = { path = "../polint-core" }
polint-diagnostics = { path = "../polint-diagnostics" }
